### ISSUE TITLE
No

### ISSUE THREAD

**Issue by igoradamenko** [narze/THIS_REPO_HAS_119_STARS#1]
![image](https://user-images.githubusercontent.com/6537798/131266084-b9717f2b-daca-4bdb-a4c0-0ed0b04f6aca.png)

**Comment by Tetracyl** [comment]
https://user-images.githubusercontent.com/29833473/131280000-5d5b269b-51ca-425f-a070-79b5e6c6622e.mp4

**Comment by narze** [comment]
It will be fixed every hour 😄

**Comment by sdwvit** [comment]
<img width="1228" alt="Screen Shot 2021-08-30 at 10 10 08 AM" src="https://user-images.githubusercontent.com/8777372/131352600-2f80102a-8cfa-45a6-9448-035863325b94.png">
please fix asap :D

**Comment by narze** [comment]
already fixed by other stars :P
